# Generated by Django 5.2.6 on 2026-05-26 10:13

import shortuuidfield.fields
from django.db import migrations, models

import apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "uuid",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=11, null=True, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(2, "已锁定"), (1, "已激活"), (0, "未激活")], default=0
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "男"), (2, "女"), (3, "其他")],
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "user_service",
            },
            managers=[
                ("objects", apps.user.models.UserManager()),
            ],
        ),
    ]
